controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    if (playerSpeed > 0) {
        playerSpeed = 1
        for (let index = 0; index < 10; index++) {
            playerSpeed += -0.2
            pause(100)
        }
    } else {
        playerSpeed += -1
        pause(2000)
    }
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    if (playerSpeed < 0) {
        playerSpeed = -1
        for (let index = 0; index < 10; index++) {
            playerSpeed += -0.2
            pause(100)
        }
    } else {
        playerSpeed += 1
        pause(2000)
    }
})
let playerSpeed = 0
let playerFall = 1
tiles.setCurrentTilemap(tilemap`level1`)
let playerSoFar = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ...........dddddddddd...........
    ...........dddddddddd...........
    ...........dddddddddd...........
    ...........dddddddddd...........
    ...........dddddddddd...........
    ...........dddddddddd...........
    ...........dddddddddd...........
    ...........dddddddddd...........
    ...........dddddddddd...........
    ...........dddddddddd...........
    ...........dddddddddd...........
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Player)
playerSoFar.setStayInScreen(true)
scene.cameraFollowSprite(playerSoFar)
forever(function () {
    if (playerSoFar.isHittingTile(CollisionDirection.Bottom)) {
        playerSoFar.vy = 0
    } else {
        playerSoFar.vy += playerFall
        playerFall += playerSoFar.vy - playerFall * 1.5
        pause(200)
    }
})
forever(function () {
    playerSoFar.vx += playerSpeed * 7
})
